### ISSUE TITLE
Commandes utilisateurs groupe

### ISSUE THREAD

**Issue by rick-gnous** [TobiBiotex/CDS-BOT#11]
**`name group` ne contient que des lettres [a→z], des chiffres [0→9] ou des caractères spéciaux : " - " ; "  " ; " & " <name group> a minimum 3 caractères et maximum 15 caractères.**

- [x] `searchgroup search <game name>` : recherche un groupe ouvert
- [x] `searchgroup list` : affiche sa liste de groupe rejoint
- [x] `searchgroup join <name group>` : rejoint le groupe si il reste encore une place disponible
- [x] `searchgroup leave <name group>` : quitte un groupe et libère la place
- [x] `searchgroup create <name group> <nombre de personne totale dans le groupe (entre 2 et 25)> <nom jeu>`
- [x] `searchgroup dissolve <name group>` : (capitaine du groupe uniquement) dissout le groupe et averti les membres de sa dissolution
- [x] `searchgroup transfert <name group> <mention membre> :` transfert le capitaine du groupe à la personne mentionné (capitaine du groupe uniquement)
- [x]  revoir la récupération des jeux via l'API Steam (cf. https://github.com/TobiBiotex/CDS-BOT/issues/11#issuecomment-907636525)

~ajout d'une description du groupe, quels achievements sont prévus, si c'est du PvP ou Coop, une description pour faire simple (https://github.com/TobiBiotex/CDS-BOT/issues/11#issuecomment-907639274), seulement capitaine peut modifier cette description~ => description dans event
- [x] ajout d'une _petite_ description du groupe

Après réu :

- [x] groupe: permettre au chef de groupe de faire des events
- [ ] groupe: ajout témoin 'finished', 'cancelled' etc => event ?
- [ ] commande pour forcer le refresh / refresh auto toutes les 5h ? pour recup infos succes etc

**Comment by Kekwel** [comment]
- [ ] revoir la récupération des jeux via l'API Steam
Actuellement, j'ai mis un appel vers https://api.steampowered.com/IStoreService/GetAppList/v1/ avec comme paramètres :
- key: STEAM_API_KEY,
- include_dlc: false,
- include_software: false,
- include_videos: false,
- include_hardware: false,
- max_results: 50000
C'est cet appel qui est le plus long

Ca retourne un array de jeux, seulement après je filtre ce tableau en fonction du nom du jeu renseigné.

Du coup je note ici de changer cette façon de récupérer les jeux en allant chercher dans notre base de données les jeux qu'on aura préalablement récupéré. Je ferais surement un autre ticket pour cette récupération

**Comment by Kekwel** [comment]
Et je rajoute aussi : 

- [ ] ajout d'une description du groupe, quels achievements sont prévus, si c'est du PvP ou Coop, une description quoi

**Comment by Kekwel** [comment]
j'ai encore zappé de rajouté le # .. cf commit 3f003f0bc946c049470a069af47f9b63a5966f8a

**Comment by Kekwel** [comment]
Je note ça aussi en amélioration : 
- Avoir un channel regroupant tous les groupes en cours, géré par le bot forcément

On pourra en reparler tout à l'heure

**Comment by Kekwel** [comment]
Je clos, si vous avez des remarques on ouvrira un nouveau ticket
