### ISSUE TITLE
Commande register

### ISSUE THREAD

**Issue by Kekwel** [TobiBiotex/CDS-BOT#15]
nom commande : `register`

Commande qui créé dans la base un nouvel utilisateur (celui qui envoie le message) s'il ne l'est pas déjà !

**Comment by Kekwel** [comment]
POUR L'INSTANT (à changer):
-> /register <id steam>: lie le compte discord et le compte steam dans la bdd
plus tard: /register -> envoie le site à l'utilisateur où il doit se connecter avec discord et lier son compte steam

**Comment by TobiBiotex** [comment]
Update (version beta) : 
-> rajouter image de profile dans l'embed de vérification
