### ISSUE TITLE
Commande: profile [<mention user | id>]

### ISSUE THREAD

**Issue by TobiBiotex** [TobiBiotex/CDS-BOT#16]
Affiche le profile de l'utilisateur qui contient : 
- Name tag
- Son steam id
- Son argent
- Son niveau + xp

Si c'est un utilisateur banni le précisé

**Comment by TobiBiotex** [comment]
Pour moi la commande est prête. Il ne reste juste pour plus tard à passer par un canvas

**Comment by Kekwel** [comment]
Si c'est prêt tu peux clore l'issue et en ouvrir en autre sur le passage en canvas ?
