### ISSUE TITLE
[BUG] PREFIX+ESPACE+COMMANDE

### ISSUE THREAD

**Issue by TobiBiotex** [TobiBiotex/CDS-BOT#23]
Erreur à investiguer !

![image](https://user-images.githubusercontent.com/38195605/132660504-778128a5-4c73-4d37-8c30-94fd3e23f404.png)

![image](https://user-images.githubusercontent.com/38195605/132660457-032e198b-8031-4083-ab31-45ca357e33ac.png)
(PS j'ai fait 2 commande différente d'où le double message)

**Comment by Kekwel** [comment]
Trouvé ! Dans les alias il faut mettre des array vide et pas "" !
