### ISSUE TITLE
Commande Admin groupe

### ISSUE THREAD

**Issue by rick-gnous** [TobiBiotex/CDS-BOT#3]
- [x] dissolvegroup <name group> : dissout un groupe
- [x] leavegroup <mention | id> <name group> : force un membre à quitter un groupe
- [x] blacklistuser <mention | id>

**Comment by Kekwel** [comment]
en attente pour `blacklistuser`, voir ce que ça signifie (plus possible de faire de commande, kick de tous les groupes/events, etc)
