### ISSUE TITLE
Commande pour récupérer les données du jeu

### ISSUE THREAD

**Issue by rick-gnous** [TobiBiotex/CDS-BOT#5]
Plusieurs bugs à résoudre dans la commande (@TobiBiotex si jamais tu peux décrire plus en détails les problèmes).

**Comment by TobiBiotex** [comment]
La ligne suivante : const { app } = await superagent.get(`https://store.steampowered.com/api/appdetails`).query({ appids: appId }); 
renvoie : app undefined

**Comment by Kekwel** [comment]
Corrigé avec l'ajout d'un fichier util [steam.js](https://github.com/TobiBiotex/CDS-BOT/blob/dev/util/steam.js)

- `STEAM_API_KEY: "votre_clé"` à renseigné dans votre config.js via https://steamcommunity.com/dev/apikey
- a revoir pour plus tard la façon dont les méthodes sont exportées. obligé de passer par ça ? : 
```js
module.exports = client => {
  client.nomMethode = async args => {
    ...
  }
}
// appel dans une des commandes
module.exports.run = async (client, message, args) => {
  client.nomMethode(args).then(...)
}
```
