### ISSUE TITLE
Acheter des clés Steam

### ISSUE THREAD

**Issue by rick-gnous** [TobiBiotex/CDS-BOT#7]
À voir comment on organise ça. Chiffrement des clés Steam dans la BDD ? Message aux admins pour qu’ils envoient la clé ? Service annexe ?

**Comment by Kekwel** [comment]
Maj suite à une discussion avec Sqweeb : 

> Sqweeb — Aujourd’hui à 15:42
> ou alors pour le moment plus simple par exemple je met GTA 5 dans la boutique
> une personne me l'achète
> je reçois un mp me disant
> que Josiane a acheté la clef
> et je vais lui filer
> et moi je récup la monnaie
> et ca serait le vendeur qui définirai le montant

> Mais on aura on va dire une base de jeu que les admins mettront dans la boutique histoire d'avoir une échelle de " valeur "

**Comment by Kekwel** [comment]
Idée commande :  

* shop list
> affiche les items présents à la vente, dans un message avec pagination
- shop sell <nom_jeu> <montant>
> propose à la vente un jeu à un montant donné
> a revoir pour le nom du jeu (a cause des espaces..)
> va créer un id, récupérable dans la liste
- shop buy <id>
> enleve le montant de l'item à acheter du porte monnaie de l'acheteur
> envoi un mp au vendeur, lui disant qu'il faut donner la clé à tel utilisateur (pseudo + #)
> donne le montant au vendeur, même si pas encore donné la clé ?
> bien loguer tout ca, pour éviter les cas de "oh j'ai rien reçu", "oh j'ai pas recu la monnaie"

**Comment by TobiBiotex** [comment]
Le shop list avec un menu ?

On devrait pas faire un sous menu pour les jeux ? 🤔

**Comment by Kekwel** [comment]
Oui, divisé en catégorie

**Comment by TobiBiotex** [comment]
Je pensais aussi pour pouvoir donner la clé à ça:
- un membre achète une clé : argent enlevé de son compte, envoie d'un log dans le salon "log-bot" (on peut changer le nom) et envoie un mp au vendeur (ou mention d'un admin si impossible de dm le vendeur)
Le jeu est retiré de la vente et on l'ajoute dans une table spéciale au item en cours de vente (avec une case possédant 3 valeurs : en attente, confirmé, annulé (avec des chiffres de 0 à 2 ?) + un id)
- le vendeur envoie la clé + preuve à un admin (délai max de 7 / 14 jours ?)
- l'admin utilisé la commande `shop admin confirm <id>` (ou autre si vous avez meilleur idée), ajout de l'argent au vendeur
En cas de cancel `shop admin cancel <id> : remboursement de l'acheteur

**Comment by Kekwel** [comment]
- [ ] 1 achat possible tous les 4 jours

**Comment by Kekwel** [comment]
Je laisse ouvert, en attendant vous pouvez tester :)
